### ISSUE TITLE
Note Compel changes

### ISSUE THREAD

**Issue by FangzV** [TheFifthRider/fate-slash-fate#3]

**Comment by FangzV** [comment]
Does this deserve its own page?

**Comment by stavvy-rotte** [comment]
Nah, probably not. I think it should go on the index page or a page that contains ported FATE mechanics, like Armor ratings, Weapon ratings, etc.

**Comment by TheFifthRider** [comment]
Nah, probably not. I think it should go on the index page or a page that contains ported FATE mechanics, like Armor ratings, Weapon ratings, etc.

**Comment by FangzV** [comment]
oops i ultimately put it under a greater aspects page because i know our party still has some general shakiness with aspects

**Comment by TheFifthRider** [comment]
That might be fine!
