### ISSUE TITLE
Roar rules

### ISSUE THREAD

**Issue by FangzV** [TheFifthRider/fate-slash-fate#4]

**Comment by FangzV** [comment]
oh, hm
> For one, when you roar and as long as you are in this state, you are limited to using the approach you used to create the Roar advantage, and the two connected approaches (see the diagram).

How do we handle "two connected approaches"?

**Comment by TheFifthRider** [comment]
Oh! I don't think I realized you could use connected approaches.

This should be pretty easy! I actually already made a diagram of the combat styles 😂

```      
      Brave
Buster     Arts
  Wild     Sneaky
      Quick
```
